defmodule GlixBackEnd.Repo.Migrations.AddFollowResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:follows, primary_key: false) do
      add :follower_id_id,
          references(:users,
            column: :id,
            name: "follows_follower_id_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :followed_id_id,
          references(:users,
            column: :id,
            name: "follows_followed_id_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:follows, "follows_follower_id_id_fkey")

    drop constraint(:follows, "follows_followed_id_id_fkey")

    drop table(:follows)
  end
end
