defmodule GlixBackEnd.Repo.Migrations.IsolatingTagResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("post_tags", "post_tags_pkey")

    alter table(:post_tags) do
      remove :tag_id
    end

    execute("ALTER TABLE \"post_tags\" ADD PRIMARY KEY (post_id)")
  end

  def down do
    alter table(:post_tags) do
      add :tag_id,
          references(:tags,
            column: :id,
            name: "post_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    execute("ALTER TABLE \"post_tags\" DROP constraint post_tags_pkey")

    execute("ALTER TABLE \"post_tags\" ADD PRIMARY KEY (post_id, tag_id)")
  end
end
