defmodule GlixBackEnd.Repo.Migrations.CommentResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :content, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "comments_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :comment_father_id,
          references(:comments,
            column: :id,
            name: "comments_comment_father_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :post_id,
          references(:posts,
            column: :id,
            name: "comments_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:comments, "comments_user_id_fkey")

    drop constraint(:comments, "comments_comment_father_id_fkey")

    drop constraint(:comments, "comments_post_id_fkey")

    drop table(:comments)
  end
end
