defmodule GlixBackEnd.Repo.Migrations.TaxonomyDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("post_tags", "post_tags_pkey")

    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :description, :text
    end

    alter table(:post_tags) do
      add :tag_id,
          references(:tags,
            column: :id,
            name: "post_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    execute("ALTER TABLE \"post_tags\" ADD PRIMARY KEY (post_id, tag_id)")
  end

  def down do
    drop constraint("post_tags", "post_tags_pkey")

    drop constraint(:post_tags, "post_tags_tag_id_fkey")

    alter table(:post_tags) do
      remove :tag_id
    end

    drop table(:tags)

    execute("ALTER TABLE \"post_tags\" ADD PRIMARY KEY (post_id)")
  end
end
