defmodule GlixBackEnd.Repo.Migrations.ContentDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :content, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "posts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:post_tags, primary_key: false) do
      add :post_id,
          references(:posts,
            column: :id,
            name: "post_tags_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:post_tags, "post_tags_post_id_fkey")

    drop table(:post_tags)

    drop constraint(:posts, "posts_user_id_fkey")

    drop table(:posts)
  end
end
