defmodule GlixBackEnd.Repo.Migrations.FixingPostTag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("post_tags", "post_tags_pkey")

    alter table(:post_tags) do
      modify :post_id, :uuid, primary_key: false
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end
  end

  def down do
    drop constraint("post_tags", "post_tags_pkey")

    alter table(:post_tags) do
      remove :id
      modify :post_id, :uuid, primary_key: true
    end
  end
end
