defmodule GlixBackEnd.Repo.Migrations.FixingFollowResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:follows), :follower_id_id, to: :follower_id

    rename table(:follows), :followed_id_id, to: :followed_id

    drop constraint(:follows, "follows_followed_id_id_fkey")

    drop constraint(:follows, "follows_follower_id_id_fkey")

    alter table(:follows) do
      modify :follower_id,
             references(:users,
               column: :id,
               name: "follows_follower_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :followed_id,
             references(:users,
               column: :id,
               name: "follows_followed_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:follows, "follows_follower_id_fkey")

    drop constraint(:follows, "follows_followed_id_fkey")

    alter table(:follows) do
      modify :followed_id_id,
             references(:users,
               column: :id,
               name: "follows_followed_id_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :follower_id_id,
             references(:users,
               column: :id,
               name: "follows_follower_id_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:follows), :followed_id, to: :followed_id_id

    rename table(:follows), :follower_id, to: :follower_id_id
  end
end
